[package]
name = "rust-workers"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"      # Use the latest version
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"     # Optional, if you want to use JSON serialization
